### ISSUE TITLE
Incorrect variance with multiple causal sites

### ISSUE THREAD

**Issue by daikitag** [tskit-dev/tstrait#101]
In tstrait version 0.0.1, the simulated effect sizes are divided by the number of causal sites, which will dramatically shrink the phenotypic variance when the number of causal sites is large.

Example of a trait simulation by using tstrait version 0.0.1.

![image](https://github.com/tskit-dev/tstrait/assets/48062118/5a1f4bae-9487-40b4-9348-8632257ed323)

Many thanks to Alison for detecting this major bug.

**Comment by daikitag** [comment]
It is advisable for future implementors of tstrait to not use the tstrait version 0.0.1, as it will simulate effect sizes having too small effects.

**Comment by daikitag** [comment]
The effect size simulation codes are fixed in https://github.com/tskit-dev/tstrait/pull/100

**Comment by daikitag** [comment]
I think that title looks good to me @jeromekelleher

**Comment by daikitag** [comment]
It seems that there are many studies that employ the simulation algorithm offered by the current tstrait version (Example: Martin et al. (2017)), though it does not align with the simulation described in some projects, such as the infinitesimal model for example (Barton et al. (2017)).
Instead of us implementing the "num_causal" term in the simulation, I think it might be worthwhile for us to completely remove the "num_causal" dependency in effect size simulation, as users can set it by themselves when they set the parameters of the trait model.

**Comment by gregorgorjanc** [comment]
@daikitag what exactly does the simulation in Barton et al. (2017) do? You say infinitesimal, but is it really infinitesimal (where we traditionally sample genetic values from a Gaussian without reference to genome and causal loci) or do they actually do genomic simulation with a set number of causal loci etc.

**Comment by gregorgorjanc** [comment]
> In tstrait version 0.0.1, the simulated effect sizes are divided by the number of causal sites, which will dramatically shrink the phenotypic variance when the number of causal sites is large.
> 
> Example of a trait simulation by using tstrait version 0.0.1.
> 
> ![image](https://user-images.githubusercontent.com/48062118/283141800-5a1f4bae-9487-40b4-9348-8632257ed323.png)
> 
> Many thanks to Alison for detecting this major bug.

Just to add here that we do expect loci to have smaller effects when there are many, but in AlphaSimR we do control for the genetic variance by scaling the effects again to get the target variance.

**Comment by daikitag** [comment]
@gregorgorjanc 
The simulation steps are indicated in detail in Barton et al. (2023) under "Numerical Examples"
https://academic.oup.com/genetics/article/225/2/iyad133/7224427?login=true
They assume that the traits are influenced by 1000 causal bi-allelic loci, and effect sizes are going to be $\pm \frac{\alpha}{\sqrt{M}}$, where $M$ is the number of causal sites (1000 in this example).

**Comment by gregorgorjanc** [comment]
OK, Nick is using the term `infinitesimal` a bit loosely here, but 1000 is lots and gives a very Gaussian like distribution. This is of course more semantics than substance!

**Comment by gregorgorjanc** [comment]
Maybe `polygenic` would be more apt;)

**Comment by daikitag** [comment]
Thank you @gregorgorjanc . I will incorporate it in the documentation.

**Comment by jeromekelleher** [comment]
So, I wonder if something we should do is add a ``normalise" option to ``sim_trait``? Like,

```python3
df = tstrait.sim_trait(ts, model, 1000, normalise="linear")
```

would do the ``1/num_causal`` normalisation of Martin et al

and 
```python3
df = tstrait.sim_trait(ts, model, 1000, normalise="sqrt")
```
would do the 1/sqrt(num_causal) that Nick and Alison like?

I'm sure the names are wrong here, but the idea is to try and make this normalisation easy for users so that they don't have to do tricky rescaling, or remember to do things like:
```
num_causal = 1000
df = tstrait.sim_trait(ts, model, num_causal)
# Normalise!
df.effect_size /= num_causal
```

Am I interpreting this correctly?

**Comment by jeromekelleher** [comment]
One thing to think about here also - should normalisation be done before or the frequency dependence rescaling when alpha != 0? This should be clearly documented.

**Comment by jeromekelleher** [comment]
OK, great. Let's try and finalise the API for ``sim_trait`` in the next PR so, moving the alpha option in here as well as providing some ways to normalise by ``num_causal``

**Comment by daikitag** [comment]
We had implemented the following:
- Remove the `num_causal` dependency on simulated effect sizes
- Add `normalise_phenotypes` and `normalise_genetic_value` functions to normalize the phenotype and genetic value output, such that the users can explicitly specify what they want for the mean and variance of the simulated traits.
Through these functions, the users can modify the variance of simulated phenotypes and genetic values without distorting their statistical properties (the simulation outputs of tstrait + normalized phenotypes by using `normalise_phenotypes` or `normalise_genetic_value` have been validated against external simulators).
The simulated phenotypes are frequently scaled after simulation is completed in various projects, so I think it is fair to say that this issue can be closed now.
However, please feel free to reopen this issue if you detect any issues.
