### ISSUE TITLE
Add statistical tests against existing simulator

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tstrait#102]
We should be testing our results statistically by comparing them against other simulators. There's no reason we can do this at the small scale.

It shouldn't be too hard to use e.g. [PhenotypeSimulator](https://hannahvmeyer.github.io/PhenotypeSimulator/index.html) on some simple simulations, and qqplot the results as a comparison with our results.

So, we would do something like:

1. Simulate a small tree sequence using msprime for say, 10 samples, and then for n replicates each do:
2. Compute phenotypes for each of the 10 individuals under a given model to get a distribution per-individual using tstrait
3. Export the data to VCF and do the same thing with an external too/ We can then compare the per-individual distributions as qqplots, which should be meaningful.

This will take some work to do, but is an important validation step.

**Comment by jeromekelleher** [comment]
See the msprime [verification.py](https://github.com/tskit-dev/msprime/blob/main/verification.py) script which does lots of this type of thing, and also the section in the msprime [developer docs](https://tskit.dev/msprime/docs/stable/development.html#statistical-tests)

**Comment by daikitag** [comment]
I am thinking about comparing tstrait with SLiM and AlphaSimR. I am planning to simulate traits and genetic information from those packages, obtain the tree sequence from the simulated genetic information, and simulate traits by using tstrait. I think that would be a good comparison, as SLiM and AlphaSimR are widely used packages.

**Comment by jeromekelleher** [comment]
If you do that though, you'll have to take into account the different processes that generate the ARG in the first place wont you?

Much simpler if you take a given ARG, and then generate traits either using tstrait, or one of the methods that are based on input sequences.

These totally don't have to be big examples, the R methods that read in the full VCF are fine.

**Comment by jeromekelleher** [comment]
To me this sounds more complicated than exporting to vcf, but if you think we can do what we need with AlphaSim, then great.

**Comment by daikitag** [comment]
I managed to compare tstrait with AlphaSimR, and we managed to observe a consistency with the results after standardizing the simulated genetic values (AlphaSimR standardizes the simulated genetic values to make sure that it is perfectly the same with the input mean and variance).
Comparison with PhenotypeSimulator sounds pretty complicated, as we need to input kinship to simulate effect sizes (https://hannahvmeyer.github.io/PhenotypeSimulator/reference/geneticBgEffects.html) and their environmental noise simulation is not using heritability values (https://hannahvmeyer.github.io/PhenotypeSimulator/reference/noiseBgEffects.html).

**Comment by daikitag** [comment]
I will upload the comparison codes soon.

**Comment by gregorgorjanc** [comment]
> Comparison with PhenotypeSimulator sounds pretty complicated, as we need to input kinship to simulate effect sizes

Yeah, don’t go into the kinship abyss

**Comment by daikitag** [comment]
I added a comparison with AlphaSimR in https://github.com/tskit-dev/tstrait/pull/108. I used various parameter combinations, and the QQ-plots look amazing
![image](https://github.com/tskit-dev/tstrait/assets/48062118/4d1a9af7-c8e8-44e1-acb0-e4343dc24c28)
![image](https://github.com/tskit-dev/tstrait/assets/48062118/dbf4c582-9302-483c-b534-0bfa9d2dcf30)

Many thanks to @jeromekelleher and @gregorgorjanc for valuable suggestions.

**Comment by daikitag** [comment]
I think now it is safe to say that tstrait's simulated genetic values are having the correct properties (or otherwise the simulation through AlphaSimR is incorrect, which is very unlikely).

**Comment by daikitag** [comment]
I should also note that the QQ-plot is not producing a straight line simply because the effect sizes are simulated from a normal distribution. For example, if scaling is not done in tstrait's genetic values (scaling is conducted in AlphaSimR), we will observe a strange QQ-plot. Thus, we can say that the simulated genetic values from both tstrait and AlphaSimR are having similar distributions.

![image](https://github.com/tskit-dev/tstrait/assets/48062118/936d60e2-652a-4116-aef9-a77aec795477)

**Comment by daikitag** [comment]
The statistical tests can be now added to tstrait by using [verification.py](https://github.com/tskit-dev/tstrait/blob/main/verification.py). All tests must be a subclass of the Test class defined in https://github.com/tskit-dev/tstrait/blob/main/verification.py#L38, and the test methods must start with ''test_''. The codes were largely adapted from [msprime/verification.py](https://github.com/tskit-dev/msprime/blob/main/verification.py), and please see its documentation for details.

**Comment by daikitag** [comment]
> We should be testing our results statistically by comparing them against other simulators. There's no reason we can do this at the small scale.
> 
> It shouldn't be too hard to use e.g. [PhenotypeSimulator](https://hannahvmeyer.github.io/PhenotypeSimulator/index.html) on some simple simulations, and qqplot the results as a comparison with our results.
> 
> So, we would do something like:
> 
> 1. Simulate a small tree sequence using msprime for say, 10 samples, and then for n replicates each do:
> 2. Compute phenotypes for each of the 10 individuals under a given model to get a distribution per-individual using tstrait
> 3. Export the data to VCF and do the same thing with an external too/ We can then compare the per-individual distributions as qqplots, which should be meaningful.
> 
> This will take some work to do, but is an important validation step.

I did this in Pull request https://github.com/tskit-dev/tstrait/pull/132, but I'm not sure if this validation step would be a good test, considering that all individuals will have a similar normal-looking distributions. So even if I use two different individuals to produce a QQ-plot, the results match.

![compare_tstrait_phenotype_ind_1_AlphaSimR_phenotype_ind_2](https://github.com/tskit-dev/tstrait/assets/48062118/880405b1-50b9-4221-9003-3baf00ec00b7)

Instead, I would like to propose a similar validation test that simplePHENOTYPES did https://github.com/samuelbfernandes/simplePHENOTYPES/blob/master/vignettes/Supplementary.pdf, and examine if the simulation output of tstrait is exactly the same as the simulation output of other packages.
I think putting a similar Notebook as this inside the paper as a supplementary material will definitely strengthen our claim that the simulation output of tstrait is correct, as a single exact test ensures that the tstrait algorithm is producing correct results.

I would like to propose that we completely ignore the QQ-plot comparison, and we instead do the following:

1. Exact test with AlphaSimR for a single trait
2. Exact test with AlphaSimR for pleiotropic trait
3. Exact test with simplePHENOTYPES for a single trait
4. Exact test with simplePHENOTYPES for pleiotropic trait
5. Exact test with ARG-Needle simulation for a single trait
6. Exact test with ARG-Needle simulation for a single trait with frequency dependence

For these exact test, we will be simulating traits + effect sizes by using an extrenal program, and we will put those effect sizes into the tstrait package to see if the simulated output will exactly match.

What do you think about this @jeromekelleher ?

**Comment by daikitag** [comment]
The exact tests are performed here (https://github.com/tskit-dev/tstrait/pull/140), but we plan to add further tests to examine the complete pipeline of the simulation framework.
