### ISSUE TITLE
Move causal state selection to ``sim_trait`` and make ``sim_genetic`` deterministic (and rename)

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tstrait#103]
I think we've made a minor architectural mistake in how we put together the modular components of a simulation which we should fix while we can. Currently, we have
```
df_trait = sim_trait(ts, num_causal, model, random_seed)
genetic_result = sim_genetic(ts, trait_df, alpha, random_seed)
```
where df_trait looks like this:
```
site_id	effect_size	trait_id
3	0.140148	0
```
and genetic_result has two  parts,  ``effect_size`` which looks like:
```
site_id	effect_size	trait_id	causal_state	allele_frequency
3	0.140148	0	G	0.2
```
and ``.genetic`` which looks like 
```
trait_id	individual_id	genetic_value
0	0	0.897513
0	1	0.793933
0	2	0.140148
0	3	0.378682
0	4	0.378682
```
While writing this up, I found it very confusing. Why are we doing it this way? Wouldn't it be much simpler to do this:
```
df_trait = sim_trait(ts, num_causal, model, alpha, random_seed)
``` 
and ``df_trait`` looks like
```
site_id	effect_size	trait_id	causal_state	allele_frequency
3	0.140148	0	G	0.2
```
and then we do
```
df_genetic = genetic_value(ts, df_trait)
```
and returns
```
trait_id	individual_id	genetic_value
0	0	0.897513
0	1	0.793933
0	2	0.140148
0	3	0.378682
0	4	0.378682
```

So, we do the choice of causal state and correction of the effect size by allele frequency within ``sim_trait``, and then the ``genetic_value`` function simply does all the propagating.

The only reason I can see for doing it in the current way is to avoid going through the trees multiple times, but I feel that this is a premature optimisation and that clarity of the modular API is more important.

Thoughts @GertjanBisschop, @daikitag?

**Comment by daikitag** [comment]
@jeromekelleher 
This is also a thing that I thought of before, but in that case, we need to do 2 tree traversal algorithms (1 for obtaining allele frequency and 1 for obtaining the genotypes).
https://github.com/tskit-dev/tstrait/blob/main/tstrait/genetic_value.py#L174 This code is the main bottleneck of the algorithm, so the simulation time will be doubled if we do the simulation like that.

Instead, what we can do is that we use the current codes for `sim_phenotype` function, and modify the `sim_trait` and `genetic_value` function as you had mentioned, so that users can use the `sim_trait` and `genetic_value` function to modify the sections of simulations, even though the simulation time might be slower.

**Comment by GertjanBisschop** [comment]
Good point @daikitag. But with your solution we would have to make every future code change in two places.
We could also add one more step by making `sim_phenotype()` equivalent to:
1. `draw_causal_state(ts, num_causal)`
2. `sim_genetic()`: deterministic propagation but returning [0, 1, ..., ploidy] for each causal state as well as the allele frequency
3. `draw_effect_size(num_causal, allele_frequency)`
4. `sim_trait()`: multiplies the result from sim_genetic() with that of `draw_effect_size()`
5. add environmental noise.

This changes the logic slightly but I find it difficult to know what `sim_trait` and `sim_genetic` exactly do from the function name anyway, not having looked at the documentation for a long time.

**Comment by jeromekelleher** [comment]
I'm pretty relaxed about having a performance drop in the first version - we're not comparing to anyone else, so I think we should focus on a clean, modular interface first. This is especially important as we're trying to push the intermediate values of tstrait as things people can reuse and interoperate with. Currently it's really quite confusing what part of the process is responsible for what.

Anyway, we only need the traverse the trees twice when we're doing frequency dependency. I bet we'll see *improved* performance on the benchmarks we've been using if we factor out needlessly computing (and reporting) the allele frequencies.

**Comment by daikitag** [comment]
@GertjanBisschop 
That sounds good, but I'm wondering about the size of the genotype matrix, as the dimension will be like (million individuals x thousands of causal sites).
If you think that it is fine for us to produce a data like that, I will try modiying the codes now.

**Comment by jeromekelleher** [comment]
Can we try it my way first @daikitag? Premature optimisation is a real thing...

**Comment by daikitag** [comment]
> Can we try it my way first @daikitag? Premature optimisation is a real thing...

I will do that right now.

**Comment by GertjanBisschop** [comment]
> @GertjanBisschop That sounds good, but I'm wondering about the size of the genotype matrix, as the dimension will be like (million individuals x thousands of causal sites). If you think that it is fine for us to produce a data like that, I will try modiying the codes now.

good point. Bad idea.
