### ISSUE TITLE
Change return type from Pandas dataframe to Xarray dataset?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tstrait#105]
Xarray is very powerful, and gives a path to scaling out to things like Dask, chunked arrays, etc. It's also the basic element in sgkit, which makes me think it's a missed opportunity if tstrait doesn't go for the same basic technology from the outset.

I think all we'd have to do really is to wrap Pandas dataframes we're currently returning with Xarray and to label the dimensions, and this would give us some great future proofing.

Again, while we're making changes, perhaps it's best to just make this one?

https://docs.xarray.dev/en/stable/index.html

https://github.com/tskit-dev/tstrait/issues/new

**Comment by benjeffery** [comment]
Just throwing in my two cents here that this sounds like a good idea!

**Comment by daikitag** [comment]
@jeromekelleher I really agree with this, as many people are more familiar with pandas (I didn't know the details of xarray before learning sgkit).
But I also agree with @benjeffery that it is a good idea to try producing the xarray output, so I will try indicating it in the documentation to describe how tstrait's output can be converted into xarray.
