### ISSUE TITLE
Change "causal_state" to "causal_allele"?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tstrait#113]
When writing this up, I found "causal allele" much easier to explain, and on reflection, I don't see any reason to use ``causal_state`` (other than to mirror the tskit terminology). I think it's much clearer what our model is if we use "causal allele" throughout.

Also go through the documentation and remove references to "causal mutation", as this is incorrect (we can have multiple causal mutations to the causal allele).

**Comment by daikitag** [comment]
I agree with that, and I will change it really soon.
