### ISSUE TITLE
Review # pragma: no cover usage

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tstrait#116]
There's a few places we're using  ``# pragma: no cover`` where we could/should be testing.

Review these and replace with crafted test cases where approporate.

 ``# pragma: no cover``  should only be used in cases where it's not *possible* to test, like in a numba jitted function.

**Comment by daikitag** [comment]
Issue resolved in https://github.com/tskit-dev/tstrait/pull/119
