### ISSUE TITLE
Degrees of freedom in standard deviation computation

### ISSUE THREAD

**Issue by daikitag** [tskit-dev/tstrait#135]
When performing validation, I realized that there is a slight discrepancy between the phenotype simulation output of tstrait and AlphaSimR, and it was due to the degrees of freedom input when computing the standard deviation https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.std.html. AlphaSimR uses $N$ as a divisor instead of $N-1$, so we should also add one more input `ddof` to `normalise_phenotypes` function, such that the user can define how the standard deviation is being computed.

**Comment by gregorgorjanc** [comment]
FYI We do this because our AlphaSimR populations have all the data so we are not calculating sample variance, but population variance

**Comment by gregorgorjanc** [comment]
Feel free to reach out for any AlphaSimR questions;)
