### ISSUE TITLE
Version 0.1.0 release

### ISSUE THREAD

**Issue by daikitag** [tskit-dev/tstrait#147]
Update tstrait version to version 0.1.0.

**Comment by daikitag** [comment]
Changelog update is in this pull request: https://github.com/tskit-dev/tstrait/pull/146

**Comment by jeromekelleher** [comment]
What's involved here @benjeffery - updating the changelog with the correct date, and then tagging? I'm never quite sure what the right process is for invoking the robots here.

**Comment by daikitag** [comment]
I created a draft of the new release here.
https://github.com/tskit-dev/tstrait/releases/tag/untagged-72ece473dc56d94b4dd0

**Comment by benjeffery** [comment]
> What's involved here @benjeffery - updating the changelog with the correct date, and then tagging? I'm never quite sure what the right process is for invoking the robots here.

Yep, push tag to build and deploy to test PyPI, then create release to push to production PyPI. Detailed in the tskit dev docs.

**Comment by daikitag** [comment]
@benjeffery I followed the things that were said here, https://tskit.dev/tskit/docs/stable/development.html#python, and would it be possible for you to see if it is working well? I can see that things are chaging in Actions tab.

**Comment by daikitag** [comment]
It seems that I created a new tag, https://github.com/tskit-dev/tstrait/releases/tag/0.1.0, and I guess it will be uploaded to PyPI once I release the tag. I saw the zip file, and I think it looks good. Would it be possible for us to publish the new version now?

**Comment by GertjanBisschop** [comment]
Should we add some release notes (copied from the changelog)?

**Comment by jeromekelleher** [comment]
What's the process for generating the release notes on GitHub @benjeffery?

**Comment by daikitag** [comment]
According to what I read msprime https://github.com/tskit-dev/msprime/releases, it might be better to copy the highlights from the changelog to release notes.

**Comment by benjeffery** [comment]
> What's the process for generating the release notes on GitHub @benjeffery?

`tstrait` doesn't have the auto-change log code that tskit does, so the right thing to do is copy them over as daiki has done.
