### ISSUE TITLE
Steps to make tstrait as a library

### ISSUE THREAD

**Issue by daikitag** [tskit-dev/tstrait#16]
- [x] `_config.yml`. It is slightly different compared with `tskit` or `msprime`.
- [x] Makefile (Is it correct?)
- [x] `build.sh`
- [ ] `README.md`
- [x] `setup.cfg`
- [x] License in `setup.cfg`
- [x] Do we have to put `dOxygen` in docs like `tskit`?
- [x] [.flake8](https://github.com/tskit-dev/tskit/blob/main/python/.flake8) in `tskit`. Should we create a similar file?
- [x] Logo (Like `tsinfer` and `tsdate`)
- [x] [.pre-commit-config.yaml](https://github.com/daikitag/tstrait/blob/main/.pre-commit-config.yaml) might not be working when I commit to github.

**Comment by daikitag** [comment]
- What badges to add in README.md?

**Comment by GertjanBisschop** [comment]
We can add codecov, docs, pypi download badges and so on once these have all been set up. This is fairly straightforward.

**Comment by daikitag** [comment]
Makefile and build.sh not deleted from the repo
