### ISSUE TITLE
Causal sites

### ISSUE THREAD

**Issue by daikitag** [tskit-dev/tstrait#24]
tstrait currently chooses causal sites at random among all the sites in the tree sequence data. We can change the Python API and provide user control of which sites could be causal. For example, the users can select the minimum and maximum allele frequency of causal sites, such that tstrait doesn't choose singletons.
stdpopsim has some functionalities that could be used for this.

**Comment by jeromekelleher** [comment]
Is this a duplicate of #53

**Comment by daikitag** [comment]
Yes, it is. Thank you for noticing it.
