### ISSUE TITLE
Add coverage

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tstrait#28]
Using codecov - @GertjanBisschop should have access to codecov if he logs in using github. Let me know if not.

**Comment by GertjanBisschop** [comment]
I don't seem to have the necessary privileges to setup the repo in circle ci.

**Comment by benjeffery** [comment]
You should do as you're in the admin group for tskit - let's look at this together Monday?

**Comment by GertjanBisschop** [comment]
Solved in #44 ad #46.
