### ISSUE TITLE
Add mergify

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tstrait#29]
See https://github.com/tskit-dev/tskit/blob/main/.mergify.yml

**Comment by GertjanBisschop** [comment]
Added mergify config.yml but do not have the necessary privileges to add the repo to mergify.

**Comment by benjeffery** [comment]
Did you get the invite for the admin role on tskit?

**Comment by GertjanBisschop** [comment]
Solved in #47 and #40.
