### ISSUE TITLE
Create Test PyPI and PyPI packages

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tstrait#33]
Needs to be done before #30

**Comment by jeromekelleher** [comment]
We manually uploaded packages for the 0.0.1a1 release today, just to get the ball rolling.

**Comment by jeromekelleher** [comment]
This is almost working now, but I'm failing at the last hurdle of uploading to pypi. I think we need to wait for @benjeffery to weave some magic here.

**Comment by benjeffery** [comment]
I'm trying out the new "Trusted Publisher Management" with this package - this means we don't have any credential management. @jeromekelleher I need to be added to the package on pypi to configure this. Currently testing on the test PyPI.
