### ISSUE TITLE
Detect site ID

### ISSUE THREAD

**Issue by daikitag** [tskit-dev/tstrait#49]
The current code does not detect an error if the causal site ID in the genetic value dataframe is not included in the tree sequence data. The error is only given at `site = self.ts.site(single_id)` in `sim_phenotype.py`, so it will be better to raise an error here if an error is caused here. Shall we put `try:` here?

**Comment by jeromekelleher** [comment]
If we get an informative error from the tskit code then I think it's ok.

Can you show an example traceback from requesting an invalid site please?

**Comment by daikitag** [comment]
![image](https://github.com/tskit-dev/tstrait/assets/48062118/6c0c5c67-cb21-457c-9aa9-fd3d8b158cce)
![image](https://github.com/tskit-dev/tstrait/assets/48062118/16babc2e-4c36-431f-88ee-0883d067d73f)
![image](https://github.com/tskit-dev/tstrait/assets/48062118/6ac01c85-57f6-4991-8973-99b7a3d9e313)

**Comment by daikitag** [comment]
We get `IndexError: Index out of bounds` as an error message from `tskit`, so it seems that we can get a clear error message from the `tskit` code.

**Comment by jeromekelleher** [comment]
I think it's fine
