### ISSUE TITLE
causal sites

### ISSUE THREAD

**Issue by GertjanBisschop** [tskit-dev/tstrait#53]
The current API assumes we provide `num_causal_sites`. It might make more sense to turn this into `causal_sites` and allow both integer values as well as numpy arrays. The case of an integer is the currently implemented behaviour. In case of an array, these should all be sites contained in the sites table. We would then no longer randomly pick sites. 

Alternatively, it might make more sense to provide an example in the documentation on how to mask certain regions of the genome with tree sequences, in case we have knowledge of coding vs non-coding regions for example.

**Comment by daikitag** [comment]
Thanks for your comment, and I think it sounds like a great idea. I will try modifying the codes and post a pull request about it really soon.

**Comment by GertjanBisschop** [comment]
Just a suggestion to make sure the API is future proof, even when we have not implemented all possibilities just yet.

**Comment by daikitag** [comment]
Instead of changing `num_causal` to `causal_sites`, I'm actually thinking about adding a new argument, `causal_id = None` as one of the arguments in addition to `num_causal`, but what do you think about it? I will try implementing the changes after https://github.com/tskit-dev/tstrait/pull/52 gets processed.

**Comment by GertjanBisschop** [comment]
That would make sense. The main goal here is I think is to add a layer of realism to the simulations by specifying regions of the genome on which we might have prior knowledge. The obvious thing being coding regions. The simplest way would probably be the way you propose using a list of `causal_id`. This list might contain 100 000 elements from which we then randomly select `num_causal_sites`. This would require preprocessing by the user. Another option would therefore be to specify a list of lists containing ranges for which to include variants. We should probably have a look at how this is done in stdpopsim.

**Comment by jeromekelleher** [comment]
I think providing the option to specify the actual causal sites is the most flexible thing, that way users can do arbitrarily complex things to choose them. There's no point in getting into choosing randomly from some other set, since that's trivial to do using numpy anyway.

**Comment by daikitag** [comment]
I just made a modification to the `sim_trait()` function to incorporate this change. Would it be possible for you to review it whenever you have some time?
https://github.com/tskit-dev/tstrait/pull/55
