### ISSUE TITLE
Audit docs requirements

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tstrait#72]
We need to audit the sphinx extensions listed in ``extra_extensions`` in the ``_config.yml`` and the ``requirements/CI-docs/requirements.txt`` to only use things that are actively used in the docs.

I guess there's some extra changes here after moving the to jupyter notebook backend (rather than IPython?) @daikitag?

**Comment by daikitag** [comment]
This should be resolved by https://github.com/tskit-dev/tstrait/pull/77
