### ISSUE TITLE
Error in rng.choice

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tstrait#94]
Originally here: https://github.com/tskit-dev/tstrait/discussions/93

```
Traceback (most recent call last):
  File "/home/rkerr/dataplan-2/tbasim/Python/demography_from_tree_example.py", line 280, in <module>
    trait_df = tstrait.sim_trait(ts_new, num_causal=nqtl, model=model, random_seed=1234)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rkerr/.local/lib/python3.11/site-packages/tstrait/simulate_effect_size.py", line 137, in sim_trait
    trait_df = simulator._sim_causal_mutation()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rkerr/.local/lib/python3.11/site-packages/tstrait/simulate_effect_size.py", line 57, in _sim_causal_mutation
    site_id_array = self._choose_causal_site()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rkerr/.local/lib/python3.11/site-packages/tstrait/simulate_effect_size.py", line 38, in _choose_causal_site
    site_id = self.rng.choice(
              ^^^^^^^^^^^^^^^^
  File "_generator.pyx", line 847, in numpy.random._generator.Generator.choice
TypeError: expected a sequence of integers or a single integer, got '400.0'
```

Can you give us a minimum working example here please @richard-Hobart so we can reproduce?

**Comment by richard-Hobart** [comment]
Thanks Jerome,
In writing a minimum working example, I managed to remove the bug and the script finished to completion. I am not completely sure what it was that generated the error. I will work on it again tomorrow and let you know. It would be good to have some warning which may prevent someone else reproducing the error.
Thanks for being so prompt in replying to my query yesterday.

**Comment by GertjanBisschop** [comment]
Looking at the last line of the error trace: `TypeError: expected a sequence of integers or a single integer, got '400.0'`. It seems like `num_causal=400.0`, so a `float` instead of an `int`. @daikitag, we are currently typechecking this parameter whenever it is called by a particular model. But not when passed to `sim_trait` I think. Could you double check this?

**Comment by daikitag** [comment]
@GertjanBisschop 
Thank you for your feedback. I actually purposelly didn't put an error detecting message there, as I thought that `numpy`'s 'rng.choice' function can detect the appropriate errors, and that is the only part where it is used in `sim_trait`. Would you suggest that I put an error detecting message there?

**Comment by GertjanBisschop** [comment]
Yep, I get your point. However, catching it early makes it easier to raise a more meaningful error message here I think.

**Comment by jeromekelleher** [comment]
Can this be closed?

**Comment by daikitag** [comment]
Yes, thank you for letting me know about it.
