### ISSUE TITLE
Document how ploidy works

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tstrait#95]
I assume that `tstrait` relies on (a) individuals being present in the tree sequence (in particular, each sample genome must belong to an individual) and (b) individuals being diploid?

It would be useful to clarify this somewhere, and state what happens e.g. if individuals are haploid, triploid, or whatever.

https://github.com/tskit-dev/tstrait/issues/27 is probably relevant here too.

**Comment by daikitag** [comment]
Hi Yan, thank you very much for your feedback.
(a) I'm sorry, but I'm not entirely sure about what you mean here. `tstrait` can simulate individuals with internal nodes, and it is extracting individuals by using `nodes_individual` property of a tree sequence https://github.com/daikitag/tstrait/blob/main/tstrait/genetic_value.py#L142. Would it be possible for you to let me know the details of the point made here?
(b) `tstrait` does not assume that individuals are diploids, and it has been tested in unit tests that it works for haploid, troploid, etc

**Comment by hyanwong** [comment]
Thanks @daikitag  - re (a), I mean that if there are no individuals in the tree sequence (e.g. if you try it on a tree sequence generated using `msprime.simulate(100, length=10000, mutation_rate=1e-2)`), it won't work. I assume you report on all the individuals in the tree sequence that have at least one sample node associated with them (what do you do with individuals which either don't have any nodes, or which have only non-sample nodes?)

re (b) - that's great, thanks. It's probably worth saying in the docs somewhere that the trait values are simply added up (are they?) over all the genomes in each individual, regardless of ploidy. This will presumably change if you implement dominance?

**Comment by daikitag** [comment]
Thank you for your feedback. For (a), I will try adding a code to raise an error when there are no individuals in the tree sequence data, as a non-informative error is raised right now. `tstrait` can work on individuals having non-sample nodes, and it is tested in unit tests.

For (b), I will add that to the documentation. I haven't implemented dominance to `tstrait` yet, as we have to check that all individuals are diploids, and I'm planning to do that in the future work.

Thank you for your suggestions.
